name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
      release_notes:
        description: 'Release notes or changelog for this version'
        required: false
        default: ''
        

jobs:
  build:
    name: 构建 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建应用
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run build:win
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build:mac
          else
            npm run build:linux
          fi
        shell: bash

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: build/

  release:
    name: 创建发布
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 下载所有构建产物
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: 显示结构
        run: ls -R
        working-directory: artifacts

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
